### ISSUE TITLE
Update documentation to reflect differences against `vinyl`?

### ISSUE THREAD

**Issue by jprichardson** [wooorm/vfile#1]
This looks pretty useful! Would you be willing to update the documentation to explain how `vfile` is different than [`vinyl`](https://github.com/wearefractal/vinyl) and what would be a good use case for one over the other? Thank you.

**Comment by wooorm** [comment]
Yup! Will do. Before I’ll get that done though, here’s the gist:

Vinyl (albeit really awesome!) is very focussed on Node.js. You can probably browserify it to include things for buffers, streams, and what-not, but that would significantly increase size.

In addition, the compatibility with ESLint’s formatters is very useful. Often, tools need to warn about some thing in some file at some position. Then you still need to format that ([eslint](https://github.com/eslint/eslint/tree/master/lib/formatters), [jscs](https://github.com/jscs-dev/node-jscs/tree/master/lib/reporters), [jshint](https://github.com/jshint/jshint/tree/master/src/reporters), and probably every other tool out there), and you end up with 50% of your code as formatters/reporters. VFile opts for normal JavaScript error objects which display nicely in node and the browser on their own, but still have ESLint compatibility.

**Comment by wooorm** [comment]
Good question btw 😉

**Comment by wooorm** [comment]
Hope this explains it :ok_hand:

**Comment by jprichardson** [comment]
> Hope this explains it 

Yep :) Thanks.
