### ISSUE TITLE
No vfile.js and vfile.min.js in the package?

### ISSUE THREAD

**Issue by tunnckoCore** [wooorm/vfile#12]
How to access them from CDNs and like? It's okey to not appear in github repo, but i think they should be in the package? Add them to `files` field?

**Comment by wooorm** [comment]
There are prebuilt distribution files on [releases](https://github.com/wooorm/vfile/releases), which I provide as a convenience.
I don’t think they should be in npm packages, if you’re using vfile like that you’ll need to use browserify or webpack.
