### ISSUE TITLE
npm install fails with v1.3.0

### ISSUE THREAD

**Issue by geek** [wooorm/vfile#4]
```
$ npm install vfile
npm ERR! Darwin 15.3.0
npm ERR! argv "/.nvm/versions/node/v5.4.1/bin/node" "/.nvm/versions/node/v5.4.1/bin/npm" "install" "vfile"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/vb/gnnlw81500xbv1j4cd9ynfv40000gn/T/npm-8503-0c22b4ae/registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
npm ERR! Expected: d272e8bb5c4adc196e6181515534ff57bfe2944f
npm ERR! Actual:   ffc1b808f0d5950e0a77bbb9c477f935324aadb0
npm ERR! From:     https://registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
```

**Comment by dominictarr** [comment]
I got this too.

**Comment by dominictarr** [comment]
it seems like something strange failed during published, my bet is that unpublishing 1.3.0 and publishing 1.3.1 will fix this (you cannot republish new code to an old version)

**Comment by geek** [comment]
@dominictarr definitely an issue on the npm server side... same request gets back 2 different files

**Comment by ednapiranha** [comment]
I had to change my registry from the default - this seems to work:

`npm set registry https://registry.nodejitsu.com`

**Comment by dominictarr** [comment]
@ednapiranha long time no see! that fix doesn't work for me. hmm.

**Comment by dominictarr** [comment]
hangon, this: `curl http://registry.nodejitsu.com/vfile/-/vfile-1.3.0.tgz | shasum` does get the correct shasum...

**Comment by wooorm** [comment]
Darn guys, sorry about this. I just introduced automatic publishing from the travis built. Seems that isn’t working as expected. I unpublished, and will try publishing 1.3.1 in a sec

**Comment by wooorm** [comment]
1.3.1 published, things are back to normal for me, how about you all?

**Comment by denysdovhan** [comment]
I have the same problems: [Travis Build](https://travis-ci.org/denysdovhan/gulp-remark/jobs/103930749)

**Comment by denysdovhan** [comment]
Now [works fine](https://travis-ci.org/denysdovhan/gulp-remark/builds/103930748)! Thanks!

**Comment by geek** [comment]
Everything works for me now, thanks for the quick turnaround.

Still seems like npm has a bug, there should be consistency on the packages being served.

**Comment by wooorm** [comment]
Thanks for posting, @geek, and @dominictarr for the tweet.

I’m not sure what happened, but I am sure that this has happened at least once before (although on a very insignificant module), on a module published from travis to npm.

I’m not sure whether it’s npm or travis, but there’s definitely something weird going on.

**Comment by dominictarr** [comment]
I've never seen this before, in all my time using npm. you should definitely bring this to the attention of the @npm team.

**Comment by wooorm** [comment]
I found the previous time I had this problem: [quotation](https://github.com/wooorm/quotation/commits/master). The release of 1.0.0 was borked, so I had to commit 1.0.1 to get it working again. I’m not sure what exactly happened, but the publish was also from Travis to npm, and I got the same error.

**Comment by geek** [comment]
@dominictarr yep, I logged an issue https://github.com/npm/npm/issues/11234
