### ISSUE TITLE
`file.quiet` should be `true` by default

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/vfile#5]
It took me a long time to figure out why `file.fail()` resulted in no output, but `file.warn()` worked fine, when using it with `vfile-reporter`.

This is what other linters does. ESLint has `warning` and `error`, neither throws, but outputs to stdout. If there are any `error` in the result, ESLint changes the exit code to 1.

**Comment by wooorm** [comment]
Weird that `file.fail()` didn’t result in any output! No uncaught exceptions either?

Interesting. I initially designed it the other way around: there’s fatal exceptions in files, but they should too be associated with files, thus the `fail` method. Then came the addition that sometimes they shouldn’t even be thrown (but still be handled as an error).

This is related to https://github.com/wooorm/remark-lint/issues/65, as you’ve already seen.

Maybe a solution would be for warnings to show up as `error / warning / message`, all from the `warn()` API.

I’ll think about it some more! 👍

**Comment by sindresorhus** [comment]
> No uncaught exceptions either?

Nope. Which made it hard to debug.

> This is related to wooorm/remark-lint#65, as you’ve already seen.

Yup. That is the real solution. Selecting what should be warning or error should be up to the end-user, not the plugin creator. But in the meantime, I think it would be good to just change `quiet` to be `true` by default so other people don't have to waste time debugging why there's no output.

**Comment by wooorm** [comment]
> > No uncaught exceptions either?
>
> Nope. Which made it hard to debug.

Do you have a minimal example which bugs out you could show me? That shouldn’t happen :(

**Comment by wooorm** [comment]
First: I fixed the root problem here, namely the swallowed exception (`trash node_modules && npm i`) 🎉 

For the `error` labels, I think https://github.com/wooorm/remark-lint/issues/65 will be the real solution for that though, so I’m deferring talk to that place.
