### ISSUE TITLE
Add test to ensure it works with ESLint formatters

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/vfile#6]
And to prevent regressions.

Could use https://github.com/sindresorhus/eslint-formatter-pretty for testing.

**Comment by sindresorhus** [comment]
I made https://github.com/sindresorhus/vfile-to-eslint. So you could drop the ESLint compatibility in the next version and just refer to that instead.

**Comment by wooorm** [comment]
Cool, that’s really awesome, thanks for working on it! 👍

Removed it from the docs now, and when GH-8 lands it’ll be removed internally too, so I’ll close this for now and defer discussion to that issue.
