### ISSUE TITLE
Add `frail` support to `hasFailed`

### ISSUE THREAD

**Issue by wooorm** [wooorm/vfile#7]
Currently, `hasFailed` returns whether any *fatal* errors occurred. As it’s often needed to check if any warnings / errors occurred, it would be useful to have support for checking that as well.

Proposed solution:

```js
var file = new VFile();
file.quiet = true;

file.hasFailed(); // false
file.hasFailed({frail: true}); // false

file.warn('Something went slightly wrong');
file.hasFailed(); // false
file.hasFailed({frail: true}); // true

file.fail('Something went wrong');
file.hasFailed(); // true
file.hasFailed({frail: true}); // true
```

Alternatively, a new `hasWarned` function could also work!

**Comment by sindresorhus** [comment]
I think you first need to figure out the story with `file.fail()` and `file.warn()`. Right now it's very confusing and limiting. Ideally it would be similar to ESLint and have `.errorCount` and `.warningCount` properties.

The option name `frail` is very unclear.

**Comment by wooorm** [comment]
This issue is superfluous with the changes coming in [2.0.0](https://github.com/wooorm/vfile/pull/10).
